version: "3"
services:
  webserver:
    build:
      context: requirements/nginx/
      dockerfile: Dockerfile
    ports:
      - "443:443"
    volumes:
      - WordPress:/var/www/html/

  website:
    build:
      context: requirements/wordpress/
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    env_file:
      - .env
    volumes:
      - WordPress:/var/www/html/

  database:
    build:
      context: requirements/mariadb/
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - db:/var/lib/mysql
      # - ./requirements/mariadb/conf/50-server.cnf:/etc/mysql/mariadb.conf.d/50-server.cnf
 
volumes:
  db:
  WordPress:
