version: "3"
services:

  database:
    build:
      context: requirements/mariadb/
    container_name: inception_mariadb
    environment:
      - MYSQL_DATABASE: "${MYSQL_DATABASE}"
      - MYSQL_USER: "${MYSQL_USER}"
      - MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      - MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"

  wordpress-fpm:
    build:
      context: requirements/wordpress/
    container_name: inception_php_fpm
    environment:
      - WORDPRESS_DB_HOST: "${WORDPRESS_DB_HOST}"
      - WORDPRESS_DB_NAME: "${WORDPRESS_DB_NAME}"
      - WORDPRESS_DB_USER: "${WORDPRESS_DB_USER}"
      - WORDPRESS_DB_PASS: "${WORDPRESS_DB_PASS}"
    volumes:
      - wp-files:/var/www/html/
    depends_on:
      - database

  webserver:
    build:
      context: requirements/nginx/
    container_name: inception_nginx
    ports:
      - "443:443"
    volumes:
      - wp_files:/var/www/html/
    depends_on:
      - wordpress-fpm

volumes:
  wp_files:
