---
version: "3.8"
services:
  database:
    build:
      context: requirements/mariadb/
    container_name: database
    env_file:
      - .env
    volumes:
      - db_volume:/var/lib/mysql
    networks:
      inception:
        ipv4_address: 172.18.0.2
  website:
    build:
      context: requirements/wordpress/
    container_name: website
    env_file:
      - .env
    volumes:
      - wp_volume:/var/www/html/
    depends_on:
      - database
    networks:
      inception:
        ipv4_address: 172.18.0.3
  webserver:
    build:
      context: requirements/nginx/
    container_name: webserver
    ports:
      - 443:443
    volumes:
      - wp_volume:/var/www/html/
    depends_on:
      - website
    networks:
      inception:
        ipv4_address: 172.18.0.4
volumes:
  wp_volume: null
  db_volume: null
networks:
  inception:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/24
          gateway: 172.18.0.1
