---
version: "3.8"
services:
  database:
    build:
      context: requirements/mariadb/
    container_name: database
    env_file:
      - .env
    volumes:
      - db_volume:/var/lib/mysql
    networks:
      inception:
        ipv4_address: 172.18.0.2
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 5
      start_period: 10s
      timeout: 5s
  website:
    build:
      context: requirements/wordpress/
    container_name: website
    env_file:
      - .env
    volumes:
      - wp_volume:/var/www/html/
    depends_on:
      database:
        condition: service_healthy
    networks:
      inception:
        ipv4_address: 172.18.0.3
  webserver:
    build:
      context: requirements/nginx/
    container_name: webserver
    ports:
      - 443:443
    volumes:
      - wp_volume:/var/www/html/
    depends_on:
      - website
    networks:
      inception:
        ipv4_address: 172.18.0.4
volumes:
  wp_volume: 
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/relkabou/data/wp_volume
  db_volume: 
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/relkabou/data/db_volume

networks:
  inception:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/24
          gateway: 172.18.0.1
