---
version: "3.8"
services:

# Mariadb
  mariadb:
    build:
      context: requirements/mariadb/
    container_name: mariadb
    env_file:
      - .env
    volumes:
      - db_volume:/var/lib/mysql
    networks:
      inception:
        ipv4_address: 172.18.0.2
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 5
      start_period: 10s
      timeout: 5s
    
# Wordpress
  wordpress:
    build:
      context: requirements/wordpress/
    container_name: wordpress
    env_file:
      - .env
    volumes:
      - wp_volume:/var/www/html/
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      inception:
        ipv4_address: 172.18.0.3

# Nginx
  nginx:
    build:
      context: requirements/nginx/
    container_name: nginx
    ports:
      - 443:443
    depends_on:
      - wordpress
    volumes:
      - wp_volume:/var/www/html/
      - ad_volume:/var/www/adminer/
    networks:
      inception:
        ipv4_address: 172.18.0.4

# FTP server
  ftp:
    build:
      context: requirements/ftp/
    container_name: ftp
    env_file:
      - .env
    ports:
      - '20:20'
    restart: on-failure
    networks:
      inception:
        ipv4_address: 172.18.0.5
  
# Adminer
  adminer:
    build:
      context: requirements/adminer/
    container_name: adminer
    env_file:
      - .env
    restart: on-failure
    depends_on:
      - wordpress
    volumes:
      - ad_volume:/var/www/adminer/
    networks:
      inception:
        ipv4_address: 172.18.0.6

# Redis
  redis:
    build:
      context: requirements/redis/
    container_name: redis
    env_file:
      - .env
    restart: on-failure
    depends_on:
      - wordpress
    networks:
      inception:
        ipv4_address: 172.18.0.7


volumes:
  wp_volume: 
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "${HOME}/data/wp_volume"
  db_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "${HOME}/data/db_volume"
  ad_volume: 
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "${HOME}/data/ad_volume"


networks:
  inception:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/24
          gateway: 172.18.0.1
